[build]
  publish = "."
  command = ""

# Mild security headers; all static so keep it simple
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
